// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdrrmqavoebgobdczdkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkcnJtcWF2b2ViZ29iZGN6ZGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjcyNjksImV4cCI6MjA2NDcwMzI2OX0.5rljwqME5Vy0kolcLb-HsGPMniHY0I8uIL79ct75jJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);